branch-defaults:
  default:
    environment: sa-site
global:
  application_name: sa_site
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.3.3
  default_region: null
  profile: sportarchive-prod
