branch-defaults:
  default:
    environment: null
global:
  application_name: sa_site_dev
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.5.0
  default_region: us-east-1
  profile: null
  sc: null
