branch-defaults:
  default:
    environment: sa-site-dev
global:
  application_name: sa_site
  default_ec2_keyname: null
  default_platform: Docker 1.3.3
  default_region: null
  profile: sportarchive-dev
  sc: null
