VAGRANTFILE_API_VERSION = "2"

require 'yaml'

docker_args = ''
YAML::load_file('.env.yml').each do |key, value|
  docker_args += " -e \"#{key}='#{value}'\""
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../sa_site-base", "/vagrant-base"

  config.vm.provision "docker" do |d|
    d.build_image "/vagrant-base", args: "-t sportarc/sa_site-base"
    d.build_image "/vagrant", args: "-t sportarc/sa_site"
    d.run "sportarc/sa_site", args: "-p 80:80" + docker_args
  end
end
